# Browser and Selenium setup
#selenium:
#  host: "localhost"
#  port: 4444

# Database environment settings
db_environment: 'automation'

# URL configuration settings
base_url: "http://sandbox46.avangate.local"
api_cart_url: "http://sandbox86.avangate.local"
# BASE_URL = "http://" + MY_HOST_NAME + ".avangate.local"
# SHORT_BASE_URL = "http://" + MY_HOST_NAME + ".avangate.local/l.php?link="
# BASE_URL_INDEPENDENT = "http://processing." + MY_HOST_NAME + ".avangate.local"
# API_URL = "http://api." + MY_HOST_NAME + ".avangate.local"
# API_CART_URL = "http://cart." + MY_HOST_NAME + ".avangate.local"
# SIGNUP_API_URI = BASE_URL + "/api/private/2.5/rpc/"
# IMPORT_MERCHANT_API_URI = BASE_URL + "/apimigration/"

# Cron running configuration
# CRON_HOST = CRON_SANDBOX + ".avangate.local"
# CRON_PATH = "/var/www/vhosts/" + CRON_SANDBOX + ".avangate.local/htdocs/linuxshell/"

cron_path_customcarts: "/var/www/stage.sandbox/htdocs/linuxshell/"
cron_user: "www-data"
user: "automation"

# Screenshots settings
screenshots_path: "tmp/jenkins/screenshots"
screenshots_url: "tmp/jenkins/screenshots"

screenshots: "tmp/jenkins/screenshots"


resources:
  chrome:
    type: Website
    ip: localhost
    port: 4444
    browser: chrome

  firefox:
    type: Website
    ip: localhost
    port: 4444
    browser: firefox

#  linux:
#    type: Unix
#    ip: sandbox86.avangate.local
#    user: www-data
#    password: automation

  mysql:
    type: Database
    ip: mysqldev.avangate.local
    user: automation
    password: withc--
    port: 3306
    db: automation